### PR TITLE
#86 refucktor arcsi play history

### PR DESCRIPTION
**Pull request by baxgas**
The Arcsi History now stores key=episode.id and playDate and seekValue for optimised store object
Thanks @pvj !

### CODE REVIEW

**Comment by gammaw** [comment]
@baxgas can you help me to understand what's the benefit of the new `Object.assign` solution compared to the `push` one that we had so far?

**Comment by baxgas** [comment]
> @baxgas can you help me to understand what's the benefit of the new `Object.assign` solution compared to the `push` one that we had so far?

@pvj 
The push method adds new entry for every listening item in the Array, the key(episodeID): value(listening info array) object stores per key - which is the unique id of the episode. So there will be only one entry per episode, which is much more optimised than storing all the listen infos. And other infos could be added also later if needed
I thought you commented about optimising it for this structure, no?
This is it:
ArcsiHistory = {
   'episodeID' : [ 
        playDate: 'time',
        playPosition: 'position'
   ],
   'episodeID' : [
        playDate: 'time',
        playPosition: 'position'
   ],
...
}

**Comment by gammaw** [comment]
@baxgas it's me gammaw not pvj :)
I see thanks, so it's a finite key-value store now instead of an infinite history list.
I won't approve it now cause you and pvj know the matter better plus I'd like to try it first, which I'll do cause I have to deal with the CORS issues anyway.

**Comment by baxgas** [comment]
Oh, sorry for misnaming :-)
CORS can be bypassed locally in Firefox, but if you are working now on fixes for it and want to test feel free.
Let me know when it can be merged, I would use this for the new player component also.

Üdv-:g

**Comment by gammaw** [comment]
@baxgas I tried the current version and I wasn't sure how to test the features. In general, what are the main use cases (user stories) where the "memory" of the player would be triggered?  

What I tried is that I 1) visited an episode page and start listening to arcsi, 2) at some point switched to home (without pausing), and 3) navigated back to the same episode page via the show page and hit play again. I was expecting the that episode starts playing where I left it but instead it started from the beginning. Note: I didn't use the browser's controls (e.g., back button).

**Comment by baxgas** [comment]
@gammaw yes, it saves the state on some interaction (pause, seek), but the browser back is not an interaction, it is just quitting the player. That's why it is better to have it somewhere always visible, as the Stream player.
Can we merge this in the main branch? If this is the only problem with it, I think it can be pushed forward in an other "bug" tracker

**Comment by baxgas** [comment]
@gammaw thank you for pointing to this case, I added the fix now, please check so we can merge

**Review by gammaw — APPROVED** [review]
I checked on ananas, now the basic functionality seems to work (remembering the playback position for every episode) so I give it an approve. I didn't check the code completely but it's a long-open PR so I think it's good to move it forward. Thanks @baxgas!

**Comment by baxgas** [comment]
Thanks @gammaw !

**Pull request merged**
