### PR TITLE
#131 improvements

### PR DESCRIPTION
**Pull request by baxgas**

### CODE REVIEW

**Comment by gammaw** [comment]
@baxgas I checked the changes (in code and tried locally), they look good to me. Any reason why it's a draft PR yet?

**Comment by baxgas** [comment]
@gammaw yes, I want to make a small function grouping change, so it is more modules, and the events can call them separately

**Comment by baxgas** [comment]
@gammaw I reworked the scripts a bit, so it is more modular and the audio play/pause events just trigger the necessary setters. Added a bit bottom margin to photos lists, since they were a bit sticking to bottom

**Review by gammaw — APPROVED** [review]
Nice updates, I tried to test the changes and checked them code-wise too. Thanks!

**Pull request merged**
