### PR TITLE
#135 small fixes

### PR DESCRIPTION
**Pull request by baxgas**
small fixes: 
- linter error messages for plugin setup
- sanitization stripping needed tags

### CODE REVIEW

**Comment by gammaw** [comment]
@baxgas all looks good, except the mobile part. I don't know if it's related with this https://github.com/mmmnmnm/lahmacun_rework/pull/136/commits/b98f9b6e7e80e1e3639c299d1be8a451d0d5c117 commit but when I now tried the mobile view, I encountered several issues: 1) the episode page didn't load properly when I arrive from home's arcsi latest div, 2) when I reloaded the episode page, the content appeared but the play button didn't start the playback (continuous wheeling on the arcsi player), and 3) (this is an issue I've been seeing every now and then) when I go back to home from a subpage by clicking on the lahma logo, the arcsi latest div doesn't load (I only see the arrows).

**Comment by baxgas** [comment]
@gammaw arcsi is DOWN?

**Comment by gammaw** [comment]
@baxgas no it wasn't due to that. I attach what I see when I click on one of the latest arcsi cards on home and then click play.

D526D341-651B-4E80-843A-F2D795A8FDB3

**Comment by gammaw** [comment]
@baxgas no it wasn't due to that. I attach what I see when I click on one of the latest arcsi cards on home and then click play.

7477717A-7D41-427E-9B1A-63E286E90B1F

**Review by gammaw — APPROVED** [review]
Looks good, disabling the link prefetch option is promising!
The arcsi player still works instable on my iPhone (doesn't start when hitting play until I start moving the seeker) but it's pobably not due to changes in this PR. We can check it out together on my phone.

**Pull request merged**
