### PR TITLE
#88 home redesign

### PR DESCRIPTION
**Pull request by baxgas**
I made the frontend according to Csenge's designs.
Questions (also asked from Csenge in Figma comments):
- player has no image now, I think it would be good to show it somehow (hover?)
- player play button should turn to pause 
- arcsi episode tags are now dummies
- I wouldn't put all the timezones in Header, makes no sense (the CET is just there for our Schedule timing)

### CODE REVIEW

**Comment by gammaw** [comment]
@baxgas I tried to build it (locally and on ananas too) and it gave this error. Any idea? 

image

**Comment by baxgas** [comment]
Did you install the new packages?
yarn install

**Comment by gammaw** [comment]
> Did you install the new packages?
> yarn install

Yes. On ananas I used docker build (see https://github.com/mmmnmnm/lahmacun_rework/blob/main/app/Dockerfile).

**Comment by baxgas** [comment]
Thanks @gammaw for the build check and notion for fixing the error. 
Please let me know if we can merge this state to the main branch

**Comment by gammaw** [comment]
So good to see that the new design is getting shape on the actual draft page! 

Nice structuring with the separate commits too! I skimmed them through quickly and they looked good to me in general. I guess we're in no hurry to merge it into main before our next meeting where we'll discuss some details of home, no? We'll probably need to change things here and there and it's nice to merge a stable version.  

One thing I noticed, under Arcsi's Latest we should add a "latency" similar to what we have for the current website on the shows subpages (so that we don't display an episode before it's premiered).

**Comment by baxgas** [comment]
@gammaw Thank you for pointing out to Arcsi Latest. Besides, I implemented a check for filtering out the not arcsived episodes. 
Also some other fixes and tweaks here-there

**Review by pvj — APPROVED** [review]
Let's see it in action!

**Comment by baxgas** [comment]
Thanks!
👍🏻🚀🧞‍♂️

**Pull request merged**
